# Generated by Django 5.1.4 on 2025-02-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["title"],
                "verbose_name": "Статья блога",
                "verbose_name_plural": "Статьи блога",
            },
        ),
        migrations.RemoveField(
            model_name="blog",
            name="publication_date",
        ),
        migrations.AddField(
            model_name="blog",
            name="publication_status",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Статус публикации"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(verbose_name="Контент"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="counter",
            field=models.BooleanField(
                default=True, verbose_name="Количество просмотров"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Заголовок"),
        ),
    ]
