# Generated by Django 5.1.4 on 2025-02-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_options_remove_blog_publication_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="publication_status",
        ),
        migrations.AddField(
            model_name="blog",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Признак публикации"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="counter",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество просмотров"
            ),
        ),
    ]
